---
title: "Writing-function"
author: "Zhiyi Zhu"
date: "2023-10-26"
output: html_document
---
```{r}
library(tidyverse)
library(rvest)
```

Set seed for reproducibility

```{r}
set.seed(12345)
```

### Z score function

```{r}
x_vec = rnorm(20, mean = 5, sd = .3)
```

Compute Z score for `x_vec`

```{r}
(x_vec - mean(x_vec)) / sd(x_vec)
```


write a function to do this

```{r}
z_score = function(x){
  
  if(!is.numeric(x)){
    stop("Argument should be numbers")
  } else if (length(x)<2){
    stop("You need at least 2 numbers to get z scores")
  }
  
  z = (x - mean(x)) / sd(x)
  
  z
  
  
}
```


check it use

```{r}
z_score(x = x_vec)

z_score(x = 3)

z_score(c("my", "name", "is", "Danica"))

z_score(c(TRUE, FALSE, TRUE, FALSE))
```

### Multiple outputs

```{r}
mean_and_sd = function(x){
  
  if(!is.numeric(x)){
    stop("Argument should be numbers")
  } else if (length(x)<2){
    stop("You need at least 2 numbers to get z scores")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```

### Getting mean and sds

```{r}
x_vec = rnorm(n = 30, mean = 5, sd = .5)

  tibble(
    mean = mean(x_vec),
    sd = sd(x_vec)
  )


```

write a function use`n`, a true mean and true SD as input

```{r}
sim_mean_sd = function(n_obs, mu, sigma){
  
  x_vec = rnorm(n = n_obs, mean = mu, sd = sigma)

  tibble(
    mean = mean(x_vec),
    sd = sd(x_vec)
  )
}

sim_mean_sd(n_obs = 300, mu = 50, sigma = 12.3)

sim_mean_sd(mu = 12, n_obs = 24, 5)
```

### Lotr words

```{r}
lotr_load_tidy = function(path = "data/LotR_Words.xlsx", cell_range, movie_name){
  
 movie_df = 
   readxl::read_excel(path, range = cell_range)|>
   mutate(movie = movie_name) |>
   janitor::clean_names() |>
   pivot_longer(
     female:male,
     names_to = "sex",
     values_to = "words"
   ) |>
   select(movie, everything())
    
 movie_df
 

}

lotr_tidy = 
  bind_rows(
    lotr_load_tidy("data/LotR_Words.xlsx", "B3:D6", "fellowship_ring"),
    lotr_load_tidy("data/LotR_Words.xlsx", "F3:H6", "two_towers"),
    lotr_load_tidy("data/LotR_Words.xlsx", "J3:L6", "return_king")) |>
  select(movie, everything())
```

### NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

data_marj = 
  nsduh_html |> 
  html_table() |> 
  nth(1) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```

write quick function

```{r}
nsduh_import = function(html, table_name, outcome_name){
  
  html |> 
  html_table() |> 
  nth(table_name) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent), 
    outcome = outcome_name) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
}

nsduh_import(nsduh_html, 1, "marj")
nsduh_import(nsduh_html, 4, "cocaine")
```















